# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModelExporter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelExporter(object):
    def setupUi(self, ModelExporter):
        ModelExporter.setObjectName("ModelExporter")
        ModelExporter.resize(1060, 598)
        self.gridLayout_2 = QtWidgets.QGridLayout(ModelExporter)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ModelExporterLayout = QtWidgets.QGridLayout()
        self.ModelExporterLayout.setObjectName("ModelExporterLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sceneListLabel = QtWidgets.QLabel(ModelExporter)
        self.sceneListLabel.setObjectName("sceneListLabel")
        self.verticalLayout.addWidget(self.sceneListLabel)
        self.sceneList = QtWidgets.QComboBox(ModelExporter)
        self.sceneList.setObjectName("sceneList")
        self.verticalLayout.addWidget(self.sceneList)
        self.objectListLabel = QtWidgets.QLabel(ModelExporter)
        self.objectListLabel.setObjectName("objectListLabel")
        self.verticalLayout.addWidget(self.objectListLabel)
        self.objectList = QtWidgets.QTreeWidget(ModelExporter)
        self.objectList.setObjectName("objectList")
        self.objectList.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.objectList)
        self.exportHeaderButton = QtWidgets.QPushButton(ModelExporter)
        self.exportHeaderButton.setObjectName("exportHeaderButton")
        self.verticalLayout.addWidget(self.exportHeaderButton)
        self.exportBinButton = QtWidgets.QPushButton(ModelExporter)
        self.exportBinButton.setObjectName("exportBinButton")
        self.verticalLayout.addWidget(self.exportBinButton)
        self.ModelExporterLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.ModelExporterLayout, 0, 0, 1, 1)
        self.modelViewGL = QtWidgets.QOpenGLWidget(ModelExporter)
        self.modelViewGL.setBaseSize(QtCore.QSize(320, 240))
        self.modelViewGL.setObjectName("modelViewGL")
        self.gridLayout_2.addWidget(self.modelViewGL, 0, 1, 1, 1)

        self.retranslateUi(ModelExporter)
        QtCore.QMetaObject.connectSlotsByName(ModelExporter)

    def retranslateUi(self, ModelExporter):
        _translate = QtCore.QCoreApplication.translate
        ModelExporter.setWindowTitle(_translate("ModelExporter", "Form"))
        self.sceneListLabel.setText(_translate("ModelExporter", "Scene"))
        self.objectListLabel.setText(_translate("ModelExporter", "Object"))
        self.exportHeaderButton.setText(_translate("ModelExporter", "Export as Header"))
        self.exportBinButton.setText(_translate("ModelExporter", "Export as Bin"))
